version: '2'
services:
  web: &app_base
    env_file: .env.production
    build:
      context: .
      dockerfile: Dockerfile.web.dev
    restart: always
    command: bundle exec puma -p 3000 -C ./config/puma.rb
    links:
      - db
      - redis
    volumes:
      - ./data/app/log:/usr/src/app/log
      - ./data/bundle:/bundle
    environment:
      RACK_ENV: production
      RAILS_ENV: production
  assets:
    build:
      context: .
      dockerfile: Dockerfile.assets.dev
    restart: 'no'
    command: yarn font sound build
    volumes:
      - ./data/assets:/usr/src/assets/assets/dist
  db:
    env_file: .env.production
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_DB: kokoroio_production
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  nginx:
    image: nginx:1.13-alpine
    restart: always
    ports:
      - "55000:80"
    links:
      - web
    volumes:
      - ./data/nginx/log:/var/log/nginx
      - ./data/assets:/usr/src/assets:ro
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./data/redis/data:/data
  command:
    <<: *app_base
    restart: 'no'
