version: '2'
services:
  web-prod:
    env_file: .env.production
    build:
      context: .
      dockerfile: Dockerfile.web.dev
      args:
        - APP_HOME=/usr/src/app
    restart: always
    command: bundle exec puma -p 3000 -C ./config/puma.rb
    links:
      - db-prod
    volumes_from:
      - bundle-prod
    volumes:
      - data-prod:/usr/src/app
    environment:
      RACK_ENV: production
      RAILS_ENV: production
  bundle-prod:
    env_file: .env.production
    build:
      context: .
      dockerfile: Dockerfile.web.dev
      args:
        - APP_HOME=/usr/src/app
    volumes:
      - data-prod:/bundle
  assets-prod:
    build:
      context: .
      dockerfile: Dockerfile.assets.dev
      args:
        - APP_HOME=/usr/src/assets
    restart: 'no'
    command: yarn run font build
    volumes:
      - data-prod:/usr/src/assets
  db-prod:
    env_file: .env.production
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_DB: kokoroio_production
      POSTGRES_USER: kokoroio_production
    volumes:
      - data-prod:/var/lib/postgresql/data
  nginx-prod:
    image: nginx:1.13-alpine
    restart: always
    ports:
      - "55000:80"
    volumes:
      - data-prod:/use/src/assets:ro
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
volumes:
  data-prod:
