FROM node:7.2.1-alpine

# Install yarn latest stable
WORKDIR /opt
RUN apk add --no-cache curl
RUN curl -L -O https://github.com/yarnpkg/yarn/releases/download/v0.23.2/yarn-v0.23.2.tar.gz
RUN tar -xvf yarn-v0.23.2.tar.gz
RUN mv dist yarn
ENV PATH /opt/yarn/bin/:$PATH

ARG APP_HOME

RUN mkdir -p /usr/src/assets
WORKDIR /usr/src/assets

COPY .babelrc       /usr/src/assets/
COPY yarn.lock      /usr/src/assets/
COPY package.json   /usr/src/assets/
COPY tsconfig.json  /usr/src/assets/
COPY webpack.config /usr/src/assets/webpack.config/
COPY tslint.json    /usr/src/assets/

RUN yarn install

COPY ./assets /usr/src/assets/assets
