FROM ruby:2.3-alpine

RUN apk --update --no-cache add \
    alpine-sdk \
    libpq \
    nodejs \
    git \
    postgresql-dev \
    linux-headers

ARG APP_HOME=/src

RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

ADD Gemfile $APP_HOME/
ADD Gemfile.lock $APP_HOME/

# for some reason, we need both of nodejs and node command
RUN ln -s /usr/bin/node /usr/bin/nodejs

RUN bundle install
