FROM ruby:2.4-alpine

RUN apk --update --no-cache add \
    alpine-sdk \
    libpq \
    nodejs \
    git \
    postgresql-dev \
    linux-headers \
    imagemagick-dev \
    imagemagick

ARG APP_HOME

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ADD ./ /usr/src/app/
ADD Gemfile /usr/src/app/
ADD Gemfile.lock /usr/src/app/

# for some reason, we need both of nodejs and node command
RUN ln -s /usr/bin/node /usr/bin/nodejs

ENV BUNDLE_GEMFILE=/usr/src/app/Gemfile \
    BUNDLE_JOBS=2 \
    BUNDLE_PATH=/bundle

