FROM ruby:2.3.1

RUN apt-get update && apt-get install -y \
    libpq-dev nodejs --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

ARG APP_HOME

RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

ADD Gemfile $APP_HOME/
ADD Gemfile.lock $APP_HOME/

# for some reason, we need both of nodejs and node command
RUN ln -s /usr/bin/nodejs /usr/bin/node

RUN bundle install
