FROM ruby:2.4-alpine

RUN apk --update --no-cache add \
    alpine-sdk \
    libpq \
    nodejs \
    git \
    postgresql-dev \
    linux-headers

ARG APP_HOME

RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

ADD Gemfile $APP_HOME/
ADD Gemfile.lock $APP_HOME/

# for some reason, we need both of nodejs and node command
RUN ln -s /usr/bin/node /usr/bin/nodejs

ENV BUNDLE_GEMFILE=$APP_HOME/Gemfile \
    BUNDLE_JOBS=2 \
    BUNDLE_PATH=/bundle

RUN bundle install
