#!/bin/bash

function run() {
  echo $1
  eval $1
}

env=$1
cmd=$2
d="docker-compose -f docker-compose.${env}.yml"

case $cmd in
  "serve") run "${d} up -d";;
  "restart") run "${d} stop && yes | ${d} rm | ${d} up -d";;
  "migrate") run "${d} exec spring bundle exec rake db:migrate";;
  "clear") run "${d} stop && yes | ${d} rm";;
  "guard") run "${d} exec spring guard";;
  "bi") run "${d} exec spring bundle exec bundle install";;
  "test") run "${d} run test";;
  "testm") run "${d} run test bundle exec rake spec:models";;
  "testv") run "${d} run test bundle exec rake spec:views";;
  "testc") run "${d} run test bundle exec rake spec:controllers";;
  "testr") run "${d} run test bundle exec rake spec:requests";;
  "testro") run "${d} run test bundle exec rake spec:routing";;
  "testh") run "${d} run test bundle exec rake spec:helpers";;
  "testp") run "${d} run test bundle exec rake spec:policies";;
  "testptn") P=$3; run "${d} run test bundle exec rspec -P ${P}";;
  "console") run "${d} exec web bundle exec rails c --sandbox";;
  "dbdrop") run "${d} exec web bundle exec rails db:drop";;
  "dbreset") run "${d} exec web bundle exec rails db:reset";;
  "dbsetup") run "${d} exec web bundle exec rails db:setup";;
  "dbseed") run "${d} exec web bundle exec rails db:seed";;
  "jsbuild") run "${d} exec assets yarn build";;
  "tslint") run "${d} exec assets npm run tslint";;
  *) run "${d} ${cmd}";;
esac
