# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15d021950b48492ee94a7e0b3eca0bb5a9854ce7b7acb16d5abe1be80d58670c98b61f2468792a981f5adf5997d266b2bb616e9f42db390fbd8295f5c8213010

test:
  secret_key_base: de5202f19c56139e8bfea9712b385b3bfb7e3cf9c4733d430cbeb142c04e580fd8bd19fb3c2a644293228ab05864a1a99faa03e808c7ac61b3b5f05e8db78d17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  s3_access_key_id: <%= ENV["S3_ACCESS_KEY"] %>
  s3_secret_access_key: <%= ENV["S3_SECRET_ACCESS_KEY"] %>
  s3_region: <%= ENV["S3_REGION"] %>
  s3_bucket: <%= ENV["S3_BUCKET"] %>
  cdn_host: <%= ENV["CDN_HOST"] %>
